---
mountOptions:
    default:    "noatime"
    btrfs:      "noatime,compress=zstd:1,space_cache=v2"
ssdExtraMountOptions:
    btrfs:    "ssd,discard=async"
crypttabOptions: "luks,keyscript=/bin/cat"
