---
kernel: linux-lts
hooks:
    - base
    - systemd
    - autodetect
    - microcode
    - modconf
    - kms
    - keyboard
    - sd-vconsole
    - block
    - plymouth
    - filesystems
    - fsck
