---
# btrfs root with EFI 512M + swap zram + snapper subvolumes.
efiSystemPartition:    "/boot"
efiSystemPartitionSize: 512M
efiSystemPartitionName: "NULLXES_EFI"

userSwapChoices:
    - none
    - file

defaultFileSystemType: "btrfs"

drawNestedPartitions: true
alwaysShowPartitionLabels: true

partitionLayout:
    -   name:       "@"
        mountPoint: "/"
        filesystem: "btrfs"
        size:       100%
        features:
            - subvolumes:
                - { path: "@",          mountPoint: "/" }
                - { path: "@home",      mountPoint: "/home" }
                - { path: "@snapshots", mountPoint: "/.snapshots" }
                - { path: "@var_log",   mountPoint: "/var/log" }
                - { path: "@var_cache", mountPoint: "/var/cache" }
                - { path: "@swap",      mountPoint: "/swap"        }

initialSwapChoice: file
swapPartitionName: "NULLXES_SWAP"

ensureSuspendToDisk: false
