---
services:
    - name: NetworkManager
      mandatory: true
    - name: greetd
      mandatory: true
    - name: systemd-timesyncd
      mandatory: false
    - name: bluetooth
      mandatory: false
    - name: cups
      mandatory: false

targets: []
