---
defaultGroups:
    - users
    - audio
    - video
    - network
    - storage
    - input
    - realtime
    - wheel

autologinGroup:  autologin
sudoersGroup:    wheel

setRootPassword:        true
doAutologin:            false
sudoersConfigureWithGroup: true
