[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# NULLXES repo (built locally during ISO build, signed at release time).
[nullxes]
SigLevel = Required DatabaseRequired
Server = file:///srv/nullxes-repo/$arch
