; xdg-desktop-portal-wlr config file.
; Installed at /etc/xdg/xdg-desktop-portal-wlr/config (or /usr/share/xdg-desktop-portal-wlr/config).

[screencast]
output_name=
max_fps=60
chooser_type=simple
chooser_cmd=

[screenshot]
output_name=
chooser_type=simple
chooser_cmd=
