//! GTK 3/4 CSS export.
//!
//! Generates `gtk-3.0/gtk.css` and `gtk-4.0/gtk.css` from the NULLXES tokens.
//! Both files share the same colour definitions; the gtk-4 file additionally
//! defines named colours that gtk-4 widgets reference internally (e.g.
//! `accent_color`, `accent_bg_color`).

use std::path::Path;

use crate::{color::*, Color, Theme};

pub fn generate(theme: &Theme, out_dir: &Path) -> std::io::Result<()> {
    let accent = theme.accent();
    std::fs::create_dir_all(out_dir.join("gtk-3.0"))?;
    std::fs::create_dir_all(out_dir.join("gtk-4.0"))?;
    std::fs::write(out_dir.join("gtk-3.0/gtk.css"), gtk3(accent).into_bytes())?;
    std::fs::write(out_dir.join("gtk-4.0/gtk.css"), gtk4(accent).into_bytes())?;
    Ok(())
}

fn rgba(c: Color) -> String {
    format!("rgba({:.0}, {:.0}, {:.0}, {:.3})",
        c.r * 255.0, c.g * 255.0, c.b * 255.0, c.a)
}

fn gtk3(accent: Color) -> String {
    format!(r#"/* NULLXES GTK 3 — generated by theme-export. Do not edit. */
@define-color theme_bg_color {bg};
@define-color theme_fg_color {fg};
@define-color theme_base_color {surf2};
@define-color theme_text_color {fg};
@define-color theme_selected_bg_color {accent};
@define-color theme_selected_fg_color {bg};
@define-color insensitive_bg_color {surf3};
@define-color insensitive_fg_color {fg_disabled};
@define-color borders {divider};

window {{
    background-color: @theme_bg_color;
    color: @theme_fg_color;
}}

button {{
    background-color: {surf3};
    color: {fg};
    border: 1px solid {divider};
    padding: 6px 12px;
    border-radius: 4px;
}}
button:hover {{ background-color: {surf4}; }}
button:active {{ background-color: {surf5}; }}
"#,
        bg          = rgba(BG),
        fg          = rgba(TEXT_PRIMARY),
        fg_disabled = rgba(TEXT_DISABLED),
        surf2       = rgba(SURFACE_2),
        surf3       = rgba(SURFACE_3),
        surf4       = rgba(SURFACE_4),
        surf5       = rgba(SURFACE_5),
        divider     = rgba(DIVIDER),
        accent      = rgba(accent),
    )
}

fn gtk4(accent: Color) -> String {
    format!(r#"/* NULLXES GTK 4 — generated by theme-export. Do not edit. */
@define-color window_bg_color {bg};
@define-color view_bg_color {surf2};
@define-color window_fg_color {fg};
@define-color view_fg_color {fg};
@define-color accent_bg_color {accent};
@define-color accent_color {accent};
@define-color accent_fg_color {bg};
@define-color destructive_bg_color {destructive};
@define-color destructive_color {destructive};
@define-color destructive_fg_color {bg};
@define-color success_bg_color {success};
@define-color success_color {success};
@define-color warning_bg_color {warning};
@define-color warning_color {warning};
@define-color error_bg_color {destructive};
@define-color error_color {destructive};
@define-color shade_color rgba(0, 0, 0, 0.36);
@define-color borders {divider};

window {{ background-color: @window_bg_color; color: @window_fg_color; }}

button.suggested-action {{ background-color: @accent_bg_color; color: @accent_fg_color; }}
button.destructive-action {{ background-color: @destructive_bg_color; color: @destructive_fg_color; }}
"#,
        bg          = rgba(BG),
        fg          = rgba(TEXT_PRIMARY),
        surf2       = rgba(SURFACE_2),
        divider     = rgba(DIVIDER),
        accent      = rgba(accent),
        destructive = rgba(DESTRUCTIVE),
        success     = rgba(SUCCESS),
        warning     = rgba(WARNING),
    )
}
